### ISSUE TITLE
Lock Screen Clock

### ISSUE THREAD

**Issue by silentcovenant** [Magisk-Modules-Repo/pirasalbegoogleproductsans#4]
I noticed that the lock screen clock on Pixel 2 XL is having issues displaying the ":" between the hour and minute numbers. It works fine on my home screen but not the lock screen for whatever reason

**Comment by dudewithafez** [comment]
Same issue in Pixel. I believe all was fine before the 2.1 update.

**Comment by pirasalbe** [comment]
Hi, it's a know issue of the font (that's the same I've been using since the first version on the repo)
I can't fix it because I didn't build the font, I just wrapped it in a module

**Comment by dudewithafez** [comment]
Can you publish all the previous versions so that I can try and find the one that's working properly. BTW thanks for this module mate one of the best.

**Comment by templatetuners** [comment]
Same here on pixel 2 XL. Still no fix?

**Comment by pazhanir** [comment]
https://github.com/Magisk-Modules-Repo/pirasalbebellotafont/issues/3

you can fix this issue like you did it to the other font.

**Comment by pulpbari** [comment]
hi guys, has anyone managed to solve?
